import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useSelector } from "react-redux";
import { wrapper } from "../store/store";
import styles from "../styles/Home.module.css";

function Home(props) {
  const [state , setState] = useState(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello World..</h1>
      <pre onClick={()=>setState('Virendrta')}>{JSON.stringify(state, null, 2)}</pre>
    </div>
  );
}

export default wrapper.withRedux(Home);
export const getServerSideProps = wrapper.getServerSideProps(
  (store) =>
    ({ req, res, ...etc }) => {
      console.log(
        "2. Page.getServerSideProps uses the store to dispatch things"
      );
      store.dispatch({ type: "TICK", payload: "was set in other page" });
      return {
        props: store.getState(),
      };
    }
);
